name: Jofalltrades
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39299
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e7f8'
    - '#262914'
    - '#00516f'
    - '#567b95'
    - '#b3b7da'
  brandStrength: 0.8125
  lightness: 0.45484139304608107
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
