name: Jofalltrades
favicon: null
layout_spectrum: 0.5621
typography_spectrum: 0.39659
title: Jacques of All Trades
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf9f5'
    - '#000000'
    - '#7398b5'
    - '#db7080'
    - '#f7d595'
  brandStrength: 0.875
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
