name: Jofalltrades
favicon: null
layout_spectrum: 0.60179
typography_spectrum: 0.39299
title: Jacques of All Trades
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272914'
    - '#fdf5f3'
    - '#ebc7b7'
    - '#d49671'
    - '#5c4c33'
  brandStrength: 0.8125
  lightness: 0.45484139304608107
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
